url: "https://demo.photoprism.org/"
title: "PhotoPrism"
subtitle: "Browse your life"
description: "Personal Photo Management powered by Go and Google TensorFlow. Free and open-source."
author: "Anonymous"
twitter: "@browseyourlife"
debug: false
read-only: false
public: false
experimental: false
admin-password: photoprism
config-path: ~/.config/photoprism
cache-path: ~/.cache/photoprism
assets-path: ~/.local/share/photoprism
resources-path: ~/.local/share/photoprism/resources
originals-path: ~/Pictures/Originals
import-path: ~/Pictures/Import
http-host:
http-mode: release
http-port: 2342
tidb-host: localhost
tidb-port: 2343
tidb-password: photoprism
database-driver: tidb
database-dsn: root:photoprism@tcp(localhost:2343)/photoprism?parseTime=true
pid-filename: ~/.local/share/photoprism/photoprism.pid
log-filename: ~/.local/share/photoprism/photoprism.log
detach-server: false
