theme: default
language: en
maps:
  animate: 0
  style: streets
features:
  archive: true
  private: true
  review: true
  upload: true
  import: true
  labels: true
  places: true
  download: true
  edit: true
  share: true
  logs: true
import:
  path: ""
  move: false
library:
  convert: true
  resample: true
  rescan: false
  group: true
