sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.travis.yml up -d
  - docker-compose exec photoprism /usr/local/go/bin/go build ./...
  - docker-compose exec photoprism /usr/local/go/bin/go run cmd/photoprism/photoprism.go migrate-db

script:
  - docker-compose exec photoprism /usr/local/go/bin/go test ./...

after_script:
  - docker-compose -f docker-compose.travis.yml down