sudo: required

services:
  - docker

before_script:
  - docker-compose -f configs/docker-compose.travis.yml up -d

script:
  - docker-compose exec photoprism make all migrate-db test

after_script:
  - docker-compose -f configs/docker-compose.travis.yml down