sudo: required

services:
    - docker

before_script:
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose exec photoprism /usr/local/go/bin/go test

after_script:
  - docker-compose down