sudo: required

services:
    - docker

before_script:
  - docker-compose -f docker-compose.travis.yml up --build -d

script:
  - docker-compose exec photoprism /usr/local/go/bin/go run cmd/photoprism/photoprism.go migrate-db
  - docker-compose exec photoprism /usr/local/go/bin/go test

after_script:
  - docker-compose -f docker-compose.travis.yml down