sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.travis.yml up --build -d
  - sleep 15
  - docker-compose exec photoprism /usr/local/go/bin/go run cmd/photoprism/photoprism.go migrate-db

script:
  - docker-compose exec photoprism /go/bin/govendor test +local

after_script:
  - docker-compose -f docker-compose.travis.yml down