sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.travis.yml up -d

script:
  - docker-compose exec photoprism make deps migrate-db js test

after_script:
  - docker-compose -f docker-compose.travis.yml down