debug: true
darktable-cli: /usr/bin/darktable-cli
assets-path: assets
thumbnails-path: assets/thumbnails
originals-path: assets/photos/originals
import-path: assets/photos/import
export-path: assets/photos/export
server-ip:
server-mode: debug
server-port: 80
database-driver: mysql
database-dsn: photoprism:photoprism@tcp(database:3306)/photoprism?parseTime=true