version: '3.3'

services:
  photoprism:
    build: .
    ports:
      - 80:80
      - 8080:8080
      - 6006:6006
      - 8888:8888
    volumes:
      - .:/go/src/github.com/photoprism/photoprism

  database:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024
    ports:
      - 13306:3306
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
      MYSQL_DATABASE: photoprism

volumes:
  database-data:
    driver: local