version: '3.5'

services:
  photoprism:
    build: .
    image: photoprism/photoprism:develop
    depends_on:
      - photoprism-db
    ports:
      - "2342:2342" # Web Server (PhotoPrism)
      - "2343:2343" # Database (built-in TiDB)
    volumes:
      - ".:/go/src/github.com/photoprism/photoprism"
    shm_size: "2gb"
    environment:
      PHOTOPRISM_URL: "http://localhost:2342/"
      PHOTOPRISM_DEBUG: "true"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_EXPERIMENTAL: "true"
      PHOTOPRISM_UPLOAD_NSFW: "false"
      PHOTOPRISM_DETECT_NSFW: "true"
      PHOTOPRISM_SERVER_MODE: "debug"
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_TIDB_HOST: "0.0.0.0"
      PHOTOPRISM_TIDB_PORT: 2343
      PHOTOPRISM_TIDB_PASSWORD: "photoprism"
      PHOTOPRISM_DATABASE_DRIVER: "tidb"
      PHOTOPRISM_DATABASE_DSN: "root:photoprism@tcp(localhost:2343)/photoprism?parseTime=true"
      PHOTOPRISM_TEST_DSN: "root:photoprism@tcp(photoprism-db:4001)/photoprism?parseTime=true"
      PHOTOPRISM_ASSETS_PATH: "/go/src/github.com/photoprism/photoprism/assets"
      PHOTOPRISM_CACHE_PATH: "/go/src/github.com/photoprism/photoprism/assets/cache"
      PHOTOPRISM_RESOURCES_PATH: "/go/src/github.com/photoprism/photoprism/assets/resources"
      PHOTOPRISM_CONFIG_PATH: "/go/src/github.com/photoprism/photoprism/assets/config"
      PHOTOPRISM_IMPORT_PATH: "/go/src/github.com/photoprism/photoprism/assets/photos/import"
      PHOTOPRISM_TEMP_PATH: "/go/src/github.com/photoprism/photoprism/assets/photos/temp"
      PHOTOPRISM_ORIGINALS_PATH: "/go/src/github.com/photoprism/photoprism/assets/photos/originals"
      PHOTOPRISM_TITLE: "PhotoPrism"
      PHOTOPRISM_SUBTITLE: "Browse your life"
      PHOTOPRISM_AUTHOR: "PhotoPrism.org"
      TF_CPP_MIN_LOG_LEVEL: 0

  photoprism-db:
    image: mariadb:10.5
    command: mysqld --port=4001 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024 --innodb-rollback-on-timeout=ON --innodb-lock-wait-timeout=120
    expose:
      - "4001"
    ports:
      - "4001:4001" # MySQL (for tests)
    volumes:
      - "./scripts/reset-test-db.sql:/docker-entrypoint-initdb.d/reset-test-db.sql"
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
      MYSQL_DATABASE: photoprism

  webdav-dummy:
    image: photoprism/webdav:20200327
