version: '3.3'

services:
  photoprism:
    build: .
    image: photoprism/photoprism:develop
    depends_on:
      - database
    ports:
      - 2342:80 # Web Server (PhotoPrism)
      - 4000:4000 # Database (MySQL compatible)
    volumes:
      - .:/go/src/github.com/photoprism/photoprism
    environment:
      PHOTOPRISM_DEBUG: "true"
      PHOTOPRISM_SERVER_MODE: "debug"
      PHOTOPRISM_ASSETS_PATH: "/go/src/github.com/photoprism/photoprism/assets"
      PHOTOPRISM_CACHE_PATH: "/go/src/github.com/photoprism/photoprism/assets/cache"
      PHOTOPRISM_IMPORT_PATH: "/go/src/github.com/photoprism/photoprism/assets/photos/import"
      PHOTOPRISM_EXPORT_PATH: "/go/src/github.com/photoprism/photoprism/assets/photos/export"
      PHOTOPRISM_ORIGINALS_PATH: "/go/src/github.com/photoprism/photoprism/assets/photos/originals"

  database:
    image: mysql:8.0.12
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
      MYSQL_DATABASE: photoprism