version: '3.3'

services:
  photoprism:
    image: photoprism/photoprism
    ports:
      - 80:80
    volumes:
      - photoprism-photos:/var/photoprism/photos

  database:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024
    volumes:
      - photoprism-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
      MYSQL_DATABASE: photoprism

volumes:
  photoprism-photos:
    driver: local
  photoprism-database:
    driver: local