version: '3.3'

services:
  photoprism:
    build: .
    image: photoprism/photoprism
    command: tail -f /dev/null
    ports:
      - 80:80
    volumes:
      - .:/go/src/github.com/photoprism/photoprism
      - ./configs/photoprism.dev.yml:/etc/photoprism/photoprism.yml:ro

  database:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024
    ports:
      - 13306:3306
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
      MYSQL_DATABASE: photoprism