debug: false
darktable-cli: /usr/bin/darktable-cli
assets-path: /srv/photoprism
cache-path: /srv/photoprism/cache
originals-path: /srv/photoprism/photos/originals
import-path: /srv/photoprism/photos/import
export-path: /srv/photoprism/photos/export
sql-host: localhost
sql-port: 4000
sql-password:
http-host:
http-mode: release
http-port: 80
http-password:
database-driver: internal
database-dsn: root:@tcp(localhost:4000)/photoprism?parseTime=true