debug: false
darktable-cli: /usr/bin/darktable-cli
assets-path: /srv/photoprism
cache-path: /srv/photoprism/cache
originals-path: /srv/photoprism/photos/originals
import-path: /srv/photoprism/photos/import
export-path: /srv/photoprism/photos/export
server-host:
server-mode: release
server-port: 80
database-driver: tidb
database-dsn: root:@tcp(localhost:4000)/photoprism?parseTime=true