debug: false
darktable-cli: /Applications/darktable.app/Contents/MacOS/darktable-cli
assets-path: /var/photoprism
thumbnails-path: /var/photoprism/thumbnails
originals-path: ~/Pictures/Originals
import-path: ~/Pictures/Import
export-path: ~/Pictures/Export
server-ip:
server-mode: release
server-port: 8080
database-driver: mysql
database-dsn: photoprism:photoprism@tcp(localhost:3306)/photoprism?parseTime=true