name: Contributors
on:
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
  push:
    branches:
      - develop
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: 'assets/static/img/contributors.svg'
          svgWidth: 800
          avatarSize: 35
          avatarMargin: 5
          affiliation: 'all'
          round: false
          sort: true
          commitMessage: 'CI: Update contributors.svg'