name: Contributors
on:
  schedule:
    - cron: '0 1 * * 0' # At 01:00 on Sunday.
  push:
    branches:
      - develop
jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.SVG_TOKEN }}
          commitMessage: 'CI: Update contributors.svg'
          svgPath: 'assets/static/img/contributors.svg'
          affiliation: 'all'
          svgWidth: 1024
          avatarSize: 60
          avatarMargin: 4
          count: 9999
          round: false
          sort: true
